name: Maven Build

on:
 push:
  branches:
   - main

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   -name: Checkout code
    uses: actions/checkout@v2

      -name: Setup Maven
       uses: actions/setup-maven@v2
       with:
        java-version:'11'

      -name: Build and package
       run: mvn clean package
